version: "3.7.5"
# python manage.py makemigrations && python manage.py migrate && 
services:
  web:
    image: poultryghana.web
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:3000 && start http://127.0.0.1:3000/"
    volumes:
      - .:/home/app/poultryghana
    ports:
      - 3000:3000
    # depends_on:
    #   - db
  # db:
  #   image: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgres/data/
    # environment:
    #   - "POSTGRES_HOST_AUTH_METHOD=trust"
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${DB_NAME}
      # - PGPORT=${DB_PORT}
      # - POSTGRES_USER=${POSTGRES_USER}
    # restart: "on-failure"

# volumes:
  # postgres_data: