# Generated by Django 3.2.16 on 2022-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='cover_image',
            field=models.FileField(null=True, upload_to='farms'),
        ),
        migrations.AddField(
            model_name='farm',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
