# Generated by Django 3.2.16 on 2022-12-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0002_auto_20221207_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poultryrecord',
            name='production_type',
        ),
        migrations.AddField(
            model_name='record',
            name='production_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
