# Generated by Django 3.2.16 on 2022-12-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0004_auto_20221208_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='poultry.farm'),
        ),
    ]
