# Generated by Django 3.2.16 on 2022-12-08 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poultry', '0005_product_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='age',
            field=models.FloatField(blank=True, help_text='in weeks', null=True),
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='culls_minus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='culls_plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record_records', to='poultry.farm'),
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='medication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weekly_records', to='poultry.record'),
        ),
        migrations.AlterField(
            model_name='poultryrecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='poultry.farm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='poultry.vetshop'),
        ),
    ]
